apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: olm-addon-default-config
spec:
# currently supported customization: OLMImage
# the same image is used for
# - olm-operator
# - catalog-operator
# - packageserver
# to deploy a different version than what is provisioned with the addon, uncomment the lines below.
# Specify different AddOnDeploymentConfigs per cluster groups to match OLM images and Kubernetes versions.
#  customizedVariables:
#  - name: OLMImage
#    value: quay.io/operator-framework/olm@sha256:3cfc40fa4b779fe1d9817dc454a6d70135e84feba1ffc468c4e434de75bb2ac5
  nodePlacement:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists